name: Fortify-on-Demand Static Analysis

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Fortify ScanCentral client for packaging
      uses: fortify/gha-setup-scancentral-client@v1
    - name: Set up Fortify-on-Demand upload
      uses: fortify/gha-setup-fod-uploader@v1
      
    - name: Checkout code from repository
      uses: actions/checkout@v2
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Package the code for uploading to FoD
      run: scancentral package -bt mvn -o package.zip    
    - name: Upload the code to FoD for static analysis
      run: java -jar $FOD_UPLOAD_JAR -z package.zip -aurl $FOD_AURL -purl $FOD_PURL -rid "$FOD_RELEASE_ID" -tc "$FOD_TENANT" -uc "$FOD_USER" "$FOD_PAT" -ep SubscriptionOnly -I 1
      env: 
        FOD_AURL: ${{ secrets.FOD_AURL }}
        FOD_PURL: ${{ secrets.FOD_PURL }}
        FOD_TENANT: ${{ secrets.FOD_TENANT }}  
        FOD_USER: ${{ secrets.FOD_USER }}
        FOD_PAT: ${{ secrets.FOD_PAT }}
        FOD_RELEASE_ID: ${{ secrets.FOD_RID }} 

    - name: Save the resulting package.zip for inspection
      uses: actions/upload-artifact@v2
      with:
        name: package.zip
        path: package.zip  
