name: Fortify-on-Demand Static Analysis

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Fortify ScanCentral client for packaging
      uses: fortify/gha-setup-scancentral-client@v1
    - name: Set up Fortify-on-Demand upload
      uses: fortify/gha-setup-fod-uploader@v1
      
    - name: Checkout code from repository
      uses: actions/checkout@v2
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Package the code for uploading to FoD
      run: scancentral package -bt mvn -o package.zip    
    - name: Save the resulting package.zip for inspection
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: package.zip
        path: package.zip  
