# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Fortify ScanCentral client for packaging
      uses: fortify/gha-setup-scancentral-client@v1
    - name: Set up Fortify-on-Demand upload
      uses: fortify/gha-setup-fod-uploader@v1
      
    - name: Checkout code from repository
      uses: actions/checkout@v2
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Package the code for uploading to FoD
      run: scancentral package -bt mvn -o package.zip        
      
